
spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/test?severTimezone=GMT%2B8
    username: mysql
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info
    org:
      springframework: info
mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
server:
  port: 8080
